# Use an OpenJDK base image
FROM openjdk:17-jdk-slim AS build

# Set the working directory
WORKDIR /app

# Copy Gradle-related files to leverage caching
COPY gradle /app/gradle
COPY gradlew /app/gradlew
COPY build.gradle.kts /app/build.gradle.kts
COPY settings.gradle.kts /app/settings.gradle.kts

# Ensure gradlew has executable permissions
RUN chmod +x gradlew

# Pre-fetch dependencies to cache them
RUN ./gradlew dependencies --no-daemon

# Copy the rest of the project files
COPY . .

# Run the fatJar task to generate the JAR file
RUN ./gradlew fatJar --no-daemon

# Use another base image for the final build
FROM openjdk:17-jdk-slim

# Set the working directory
WORKDIR /app

# Copy the JAR file from the build stage to the container
COPY --from=build /app/build/libs/ktor-pushnotification-fcm-0.0.1-all.jar app.jar

# Expose the port your app will run on
EXPOSE 8080

# Run the application
CMD ["java", "-jar", "app.jar"]
